name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application-secret.yml file
        run: |
          echo "${{ secrets.APPLICATION_SECRET_YML }}" > ./src/main/resources/application-secret.yml

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR with Jib
        run: |
          ./gradlew jib --image=730335516193.dkr.ecr.ap-northeast-2.amazonaws.com/coconote/coconote_be:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to Ubuntu Machine
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.UBUNTU_HOST }}
          username: ${{ secrets.UBUNTU_USER }}
          key: ${{ secrets.UBUNTU_SSH_KEY }}
          port: ${{ secrets.UBUNTU_PORT }}
          script: |
            cd /home/jsangmin/project/coconote
            
            # AWS CLI 설치 확인 및 설치
            if ! command -v aws &> /dev/null; then
              echo "AWS CLI가 설치되지 않았습니다. 설치 중..."
              sudo apt-get update
              sudo apt-get install -y unzip curl
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              rm -rf awscliv2.zip aws
            fi
            
            # Docker 설치 확인 및 설치
            if ! type docker > /dev/null; then
              echo "Docker가 설치되지 않았습니다. 설치 중..."
              sudo apt-get update && sudo apt-get install -y docker.io
            else
              echo "Docker가 이미 설치되어 있습니다."
            fi
            
            # Docker Compose 설치 확인 및 설치
            if ! docker-compose version > /dev/null 2>&1; then
              echo "Docker Compose가 설치되지 않았습니다. 설치 중..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            # AWS ECR 로그인
            aws ecr get-login-password --region ap-northeast-2 | sudo docker login --username AWS --password-stdin 730335516193.dkr.ecr.ap-northeast-2.amazonaws.com
            
            # Docker Compose 실행
            docker-compose pull coconote_app
            docker-compose up -d
